apiVersion: v1
kind: Service
metadata:
  name: devops-task
spec:
  type: {{ .Values.service.type }}
  selector:
    app: devops-task
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
